### PR TITLE
Don't Make ZenScript files format like Java.

### PR DESCRIPTION
**Pull request by jaredlll08**

### CODE REVIEW

**Comment by FallenEagle1** [comment]
Care to explain or elaborate on this any?

**Comment by Darkere** [comment]
Jared made proper formatting for .zs files and submitted them to github. So forcing it to java is no longer necessary.

**Comment by FallenEagle1** [comment]
I get the intent, more of asking why. I dont know why it was that way in the first place, but having explanations of why having the change now allows for a more clear understanding for anyone looking at this. Does having java force on zen cause issues, or is it just for how it looks? Things of that nature. I'm not opposed of the change, just detail oriented to keep things clear.

**Comment by jaredlll08** [comment]
https://twitter.com/jaredlll08/status/1136621677360701440

Github now has support for ZenScript, all that line does is make it be highlighted as Java, which is no longer needed.

**Comment by FallenEagle1** [comment]
Thank you. I'll leave open for the moment to remind me to get the rest of the packs once off of work.

**Pull request merged**
