### PR TITLE
Added Recipe for the Excavate Enchantment from OE Integration

### PR DESCRIPTION
**Pull request by ReiDaTecnologia**
As you should know OreExcavation Integration remove you ability to vein mine and to use it you need or a modifier for the TiC tools or a Enchantment called "Excavate" to the normal tools (Like a drill) but sadly the Excavate Enchantment don't have a recipe and to get it you need use the vanilla way that is luck based and this is not cool (Similar to LootBox),
I added a recipe for it using the Enchanters from Thermal Expansion and EnderIO.

### CODE REVIEW

**Comment by OrdinatorStouff** [comment]
I like this idea I have two initial thoughts:
1) enchant IDs (numeric) are not static from one world to the next. Bloodwork had some difficulties when creating OEIntegration when he tried to add a recipe for the book but couldn't get the ID to be reliable consistent. For that reason, I believe the entorcelator recipe could be inconsistent and might be better off without that one

2) the enchant maxes out at V (I think?) whereas the modifer maxes out at 20/20. I would prefer the enchant need at least 4 or 5 of the modifiers (instead of just 1) for level 1 of the enchant.

**Comment by ReiDaTecnologia** [comment]
5 modifiers for each level? will be in total 50! but if the player is advanced enough should get all the resources for it as the really hard resource is the manyullyn. I will remove the Arcane Entorcelator because of that sad issue.

**Comment by OrdinatorStouff** [comment]
have you tested it in-game? Can you launch with these changes and add a screenshot of the recipe in the EIO enchanter (and also test to see if actually crafts, and the book it crafts is excavate enchant as intended, AND when added to a tool does the excavate on blocks)

**Comment by ReiDaTecnologia** [comment]
I already tested but not the vein mine in the tools as it should work. Give a minute.

**Pull request merged**
