### PR TITLE
Hiding Items in JEI

### PR DESCRIPTION
**Pull request by Darkere**
Things Hidden by JEI
Almost all of them still have the default item shown.
- AA coloured Drills (make finding the actual recipe a pain)
- Painted Items from Bibliocraft (when looking up the recipe there is an animation for all colours)
- Weedwoodbucket, syrmorite bucket liquids (all)
- Claybucket liquids
- dyed Dark utils lore tag (description says it can be dyed)
- EnderIO soul vials
- EnderIO broken spawners
- EnderIO colored glass
- ME Fluid pattern liquids
- Forestry Cans and Capsules liquids
- Forge Microblock covers
- ic2 universal fluid cell liquids
- Mek gas tanks (with gasses)
- Open Blocks Tank liquids
- Pressure pipes Canister liquids
- Tech reborn cell liquids
- Thermal Florb liquids
- Thermal Morbs (might be worth keeping for looking up what can be captured)
- tinkers shards
- Tinkers stencil table,part builder
- Tinkers one material tools (all)
- Carreer bees Bark and pheromone vials (all)
- Backpack colored Backpacks 
- gendustry samples

liquids means that the item had an item version appear for every fluid type in the game.

Things I wanted to hide but couldn't.
(Where I can only hide everything or nothing. 
For some reason it works for some but not for others)
- Agricraft 
- ae2 facades
- exu2 biome markers
- gendustry Templates
- IE projector
- RFtools syringe
- Drawers

Under Consideration
- Tinkers tool parts (Nice to have for looking up tool part stats but there are a ton)
- Pollen,larvae (might needed for breeding?)
- some of the millions of wood door/fence/stairs
- some of chisel (Usually you can find these when actually chiseling a block)
- Tool forge (funnily enough it only has a few types, the config was enabled because of stencil table etc.)

Any thoughts ideas on what should be hidden/not be hidden?
I'm super biased as I'm not a person who plays for the prettyness of anything so if there is anything go ahead.

### CODE REVIEW

**Comment by Darkere** [comment]
😄 This entire thing was initially made because only the electric steel tool forge version appeared in JEI. I initially wanted to just show the Iron one but as it turns out there are not that many and the knowledge about what kind of metal you can use is not worthless.
The same config also hid hundreds of different stencil tables and part builders so it was necessary.

**Comment by FallenEagle1** [comment]
This was something discussed in discord a couple times, so there were some things talked about for it. I'm going to play around with the changes just to see all what was disabled and will go from there. Initial look this should be fine, just want to check one or two things.

**Comment by FallenEagle1** [comment]
I'm going to wait a couple days on this, mainly because I want the new ae2 mod version. This will allow for hiding all but one of the facades, so that will remove my one hesitation with some of this. Will probably make some changes along with this, but at the very least want to wait for the ae2 change to be in.

**Comment by Darkere** [comment]
Go ahead change everything lol. But yeah hiding AE2 facades would be nice. There are multiple pages of that...

**Pull request merged**
